### ISSUE TITLE
Add village/SC: "Khorkikalan/ Rathiwas"

### ISSUE THREAD

**Issue by rajdevb** [francineloza/HIM_Operations#21]
ANM: Lilawati (w/o Sombir Yadav)
Login: lilawati3661
Password: 1503

District: Mewat
PHC: Taura (3_11) --- she is not really in Tauru, but this is what we have in the dta because her SC, Rathi Bass, _was_ in PHC Tauru before
SC: Rathiwas 
Village: Khorkikalan

**Comment by rajdevb** [comment]
Hi @francineloza 

I've added the above village (so she can see it in her tablet) but we need to add two other villages in the same SC for this ANM. This a non-sample SC, so I'm not sure if the process is the same as adding villages. The villages are below: 
1) SC Rathiwas- **Khoribastand**
2) SC Rathiwas- **Sunari**

If you could add these to the server and then move them to the ANM's village list, that'd be great. I will be travelling tomorrow, so I won't be able to move the villages to her list. She has session camps tomorrow, so hopefully we can get this done by tomorrow morning (January 26) India time. 
Thanks!

**Comment by rajdevb** [comment]
Hi Francine, 

Sorry about the confusion -- the ANM has been calling our hotline everyday, and it turns out she didn't give a full list of the villages she covers. Again, not a big problem, because she isn't in our sample (I'll make a separate issue about that so that we know to drop her), but we need to change her final village list as soon as possible. 

Her final list should be as follows. 

- SC Rathiwas- Khorikalan
- SC Rathiwas- Khorikhurd
- SC Rathiwas- Rangala
- SC Rathiwas- SC Sunari

Thanks!

**Comment by rajdevb** [comment]
Hi Francine, 

Lilawati's village list currently has: Sunari, Khorkikalan.
Can we please add Rangala and Khorikhurd asap?

Also, just saw that there is a "SC Rathibass- SC Sunari" entry in our village list (by looking at the village number, I think it was added later), and we also have "SC Rathibass- Sunari". Do we know why we have both?

Thanks so much

**Comment by francineloza** [comment]
They should all be on the server? I added them on Friday. 

They are not on the server?

**Comment by francineloza** [comment]
I am confused- 

look at the post above, you said to add the following:
SC Rathiwas- Khorikalan
SC Rathiwas- Khorikhurd
SC Rathiwas- Rangala
SC Rathiwas- SC Sunari

and they should all be there?

**Comment by rajdevb** [comment]
I've attached a screenshot of what I'm seeing on the village list from the server.

![lilawati](https://cloud.githubusercontent.com/assets/25205579/22467241/e2e11b84-e7e9-11e6-9ea2-8a59e126d6eb.PNG)

**Comment by francineloza** [comment]
so basically just rangala is missing?

**Comment by francineloza** [comment]
can you confirm that the village list in your post above is the right one?

**Comment by rajdevb** [comment]
To the best of my knowledge, yes. Right now, they are in SC Rathibass (not Rathiwas), so we can keep it that way (just transliteration problems). 

Khorikhurd is also missing, not just Rangala. 

The final village list is: 
- SC Rathiwas- Khorikalan
- SC Rathiwas- Khorikhurd
- SC Rathiwas- Rangala
- SC Rathiwas- Sunari

**Comment by francineloza** [comment]
I've added them and assigned them to her, sorry about the misspelling. I dont know how to fix it at the moment, but am looking into iit. In any case (- misspelling) she should be good to go. 

Thanks!

**Comment by rajdevb** [comment]
I can see the following villages on the tablet: 
- Khorikalan
- Khoribastand
- Sunari
- Rangala

We still need to delete Khoribastand and add Khorikhurd. 

Regarding the misspelling, I think we should go with it as it is, and if the ANM complains, we can take it to Eric.

**Comment by francineloza** [comment]
Great! Thanks! 

You should be able to remove those from the server (the way you assign villages with other ANMS) let me know if you run into any issues! 

Thanks

**Comment by rajdevb** [comment]
Still seeing the same list! Ive attached the screenshot. 

Maybe once they're on the server, you can check if they're there and it'll be quicker that way?
![lilawati1](https://cloud.githubusercontent.com/assets/25205579/22495888/f6546f82-e86a-11e6-8cc5-a98dedc1a65e.PNG)

**Comment by rajdevb** [comment]
Hey, you said you pushed the correct village list to the server before you went to bed, but I'm still seeing the wrong villages. Maybe you can check the village list on the server too to see what Im' saying?

Do you think  we should ask Niki to help us for this case? This ANM keeps complaining to our field staff

**Comment by francineloza** [comment]
Done?

**Comment by rajdevb** [comment]
Yup! Now it's fine.
