### ISSUE TITLE
Create logins for our field staff

### ISSUE THREAD

**Issue by rajdevb** [francineloza/HIM_Operations#22]
Usernames "fieldstaff001" to "fieldstaff030" with passwords "him001" to "him030", respectively 
- Include only dummy villages

**Comment by francineloza** [comment]
This should have been done- are you not able to see them?

**Comment by rajdevb** [comment]
Ah great! Didn't know it was done. We'll assign them to the field staff then. 

Thanks! (I'm closing this issue in that case)
